"""AMZ_Designy - ISO country code to pytrends pn mapping."""

from __future__ import annotations

# Mapping from ISO 3166-1 alpha-2 to pytrends 'pn' parameter values
# Source: pytrends internal country name formatting
ISO_TO_PYTRENDS_PN: dict[str, str] = {
    "US": "united_states",
    "GB": "united_kingdom",
    "SA": "saudi_arabia",
    "AE": "united_arab_emirates",
    "CA": "canada",
    "AU": "australia",
    "DE": "germany",
    "FR": "france",
    "IT": "italy",
    "ES": "spain",
    "NL": "netherlands",
    "BE": "belgium",
    "CH": "switzerland",
    "AT": "austria",
    "SE": "sweden",
    "NO": "norway",
    "DK": "denmark",
    "FI": "finland",
    "PL": "poland",
    "CZ": "czech_republic",
    "HU": "hungary",
    "RO": "romania",
    "BG": "bulgaria",
    "HR": "croatia",
    "SI": "slovenia",
    "SK": "slovakia",
    "LT": "lithuania",
    "LV": "latvia",
    "EE": "estonia",
    "IE": "ireland",
    "PT": "portugal",
    "GR": "greece",
    "MT": "malta",
    "CY": "cyprus",
    "LU": "luxembourg",
    "JP": "japan",
    "KR": "south_korea",
    "IN": "india",
    "ID": "indonesia",
    "TH": "thailand",
    "VN": "vietnam",
    "MY": "malaysia",
    "PH": "philippines",
    "SG": "singapore",
    "TW": "taiwan",
    "HK": "hong_kong",
    "NZ": "new_zealand",
    "MX": "mexico",
    "BR": "brazil",
    "AR": "argentina",
    "CL": "chile",
    "CO": "colombia",
    "PE": "peru",
    "VE": "venezuela",
    "UY": "uruguay",
    "PY": "paraguay",
    "BO": "bolivia",
    "EC": "ecuador",
    "ZA": "south_africa",
    "EG": "egypt",
    "NG": "nigeria",
    "KE": "kenya",
    "GH": "ghana",
    "TZ": "tanzania",
    "UG": "uganda",
    "ZW": "zimbabwe",
    "MA": "morocco",
    "TN": "tunisia",
    "DZ": "algeria",
    "IL": "israel",
    "TR": "turkey",
    "RU": "russia",
    "UA": "ukraine",
    "BY": "belarus",
    "KZ": "kazakhstan",
    "UZ": "uzbekistan",
    "AZ": "azerbaijan",
    "GE": "georgia",
    "AM": "armenia",
    "MD": "moldova",
    "KG": "kyrgyzstan",
    "TJ": "tajikistan",
    "TM": "turkmenistan",
    "CN": "china",
    "PK": "pakistan",
    "BD": "bangladesh",
    "LK": "sri_lanka",
    "NP": "nepal",
    "MM": "myanmar",
    "KH": "cambodia",
    "LA": "laos",
    "MN": "mongolia",
    "KP": "north_korea",
    "IS": "iceland",
    "AL": "albania",
    "BA": "bosnia_and_herzegovina",
    "ME": "montenegro",
    "MK": "north_macedonia",
    "RS": "serbia",
    "XK": "kosovo",
    "AD": "andorra",
    "MC": "monaco",
    "LI": "liechtenstein",
    "SM": "san_marino",
    "VA": "vatican_city",
    "GI": "gibraltar",
    "FO": "faroe_islands",
    "GL": "greenland",
    "SJ": "svalbard_and_jan_mayen",
    "AX": "aland_islands",
    "GG": "guernsey",
    "JE": "jersey",
    "IM": "isle_of_man",
    "AW": "aruba",
    "CW": "curacao",
    "SX": "sint_maarten",
    "BQ": "bonaire",
    "AI": "anguilla",
    "BM": "bermuda",
    "KY": "cayman_islands",
    "FK": "falkland_islands",
    "GF": "french_guiana",
    "GP": "guadeloupe",
    "MQ": "martinique",
    "RE": "reunion",
    "YT": "mayotte",
    "NC": "new_caledonia",
    "PF": "french_polynesia",
    "WF": "wallis_and_futuna",
    "PM": "saint_pierre_and_miquelon",
    "BL": "saint_barthelemy",
    "MF": "saint_martin",
    "TF": "french_southern_territories",
    "IO": "british_indian_ocean_territory",
    "VG": "british_virgin_islands",
    "TC": "turks_and_caicos_islands",
    "MS": "montserrat",
    "PN": "pitcairn",
    "SH": "saint_helena",
    "GS": "south_georgia",
    "CC": "cocos_islands",
    "CX": "christmas_island",
    "NF": "norfolk_island",
    "HM": "heard_island_and_mcdonald_islands",
    "AS": "american_samoa",
    "GU": "guam",
    "MP": "northern_mariana_islands",
    "PR": "puerto_rico",
    "UM": "united_states_minor_outlying_islands",
    "VI": "virgin_islands",
    "WF": "wallis_and_futuna",
}

# Default fallback for unknown countries
DEFAULT_PN = "united_states"


def get_pytrends_pn(geo: str) -> str:
    """Convert ISO country code to pytrends 'pn' parameter.
    
    Args:
        geo: ISO 3166-1 alpha-2 country code (e.g., "US", "GB", "SA")
        
    Returns:
        pytrends pn value (e.g., "united_states", "united_kingdom")
    """
    return ISO_TO_PYTRENDS_PN.get(geo.upper(), DEFAULT_PN)


def is_supported_geo(geo: str) -> bool:
    """Check if the given ISO country code is supported."""
    return geo.upper() in ISO_TO_PYTRENDS_PN
